# Generated by Django 6.0 on 2026-04-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_image_project_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_images',
            name='image',
            field=models.ImageField(upload_to='Project_Images/'),
        ),
    ]
